# https://pnpm.io/pnpm-workspace_yaml
---
packages:
  - "internals/*"
  - "packages/*"

# https://pnpm.io/catalogs
catalog:
  "@types/estree": "~1.0.0"
  "esrap": "^1.4.0"
  "svelte": "^5.33.0"
  "typescript": "^5.8.3"
  "zimmerframe": "^1.1.0"
