name: CI & CR
# NOTE: CI -> Continuous Integration
# NOTE: CR -> Continuous Releases

on:
  pull_request:
    branches: [main, next]
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches: [main, next]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CI: true

permissions:
  checks: write
  contents: write
  id-token: write
  issues: write
  pages: write
  pull-requests: write

jobs:
  ci_lint:
    name: Lint
    uses: ./.github/workflows/ci_lint.yml
    secrets: inherit

  ci_test:
    name: Test
    uses: ./.github/workflows/ci_test.yml
    secrets: inherit

  cr_pr_preview:
    name: Publish
    uses: ./.github/workflows/cr_pr-preview.yml
    needs: [ci_lint, ci_test]
    secrets: inherit

  cr_docs:
    name: Publish
    uses: ./.github/workflows/cr_docs.yml
    needs: [ci_lint, ci_test]
    secrets: inherit
    with:
      type: ${{ github.event_name == 'pull_request' && contains(fromJson('["opened", "reopened", "synchronize"]'), github.event.action) && 'pr-preview' || 'deploy' }}
