name: Biome

on:
    workflow_call:
    workflow_dispatch:

defaults:
    run:
        shell: bash

env:
    CI: true

permissions:
    contents: read
    pull-requests: write

jobs:
    biome:
        name: Biome
        runs-on: macos-latest
        timeout-minutes: 1
        steps:
            # https://github.com/actions/checkout
            - name: Checkout to the repository
              uses: actions/checkout@v4

            # https://github.com/mongolyy/reviewdog-action-biome
            - name: Run Biome to review
              uses: mongolyy/reviewdog-action-biome@v1
              with:
                  fail_level: error
                  github_token: ${{ secrets.github_token }}
                  reporter: github-pr-review
