name: check

on:
    workflow_call:
    workflow_dispatch:

defaults:
    run:
        shell: bash

env:
    CI: true

permissions:
    contents: read

jobs:
    check:
        name: check
        runs-on: macos-latest
        timeout-minutes: 2
        steps:
            # https://github.com/actions/checkout
            - uses: actions/checkout@v4

            # TODO: Remove this step once this issue is resolved: https://github.com/pnpm/pnpm/issues/9029
            - run: npm install --global corepack

            # https://nodejs.org/api/corepack.html
            - name: Enable corepack (for pnpm)
              run: corepack enable

            # https://github.com/actions/setup-node
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  cache: pnpm
                  node-version-file: ".node-version"

            # https://pnpm.io/cli/install
            - name: Install Node.js dependencies with pnpm
              run: >
                  pnpm install
                  --frozen-lockfile

            - name: Check types with TypeScript recursively
              run: pnpm run --recursive check
