name: Labeler
on:
    - pull_request_target

jobs:
    labeler:
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            # https://github.com/actions/labeler
            - uses: actions/labeler@v5
