name: Prepare release

on:
    push:
        branches: [main]

defaults:
    run:
        shell: bash

env:
    CI: true

permissions:
    contents: write
    id-token: write
    pull-requests: write

jobs:
    prepare-release:
        name: Prepare release PR
        if: "!contains(github.event.head_commit.message, 'chore: Prepare release')" # Skip merges from releases
        runs-on: ubuntu-latest
        steps:
            # https://github.com/actions/checkout
            - uses: actions/checkout@v4

            - name: Configure Git
              run: |
                  git config --global user.name GitHub Actions
                  git config user.email github-actions@github.com

            # https://github.com/biomejs/setup-biome
            - name: Setup Biome
              uses: biomejs/setup-biome@v2
              with:
                  version: latest

            # https://github.com/knope-dev/action
            - uses: knope-dev/action@v2.1.0
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            # https://knope.tech/recipes/1-preview-releases-with-pull-requests/
            - run: knope prepare-release --verbose
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
